#!/usr/bin/ruby
# -*- coding: utf-8 -*-

#require 'termcolor'
#system('/bin/bash ~/.bash_profile')

#%x['/bin/bash' '/home/pankaj/.bash_profile']

git_status = %x['git' 'status']
#x['rvm use ruby-1.9.2-p290@onions']

if git_status =~ /working directory clean/
  #puts "☘"
  #puts "☻"
  if git_status =~ /branch is ahead/
    out = puts "☯" #+ "{git_status.to_a[1].split(/*..commits/)}"
  else
    puts "☯"
  end

  #puts "⚑"
elsif git_status =~ /Changes to be committed/
  puts "♻"
  #puts "♺"
elsif git_status =~ /Changes not staged for commit:/ 
  puts "☢"
  #puts "⚔"
elsif git_status =~ /Untracked files/
  puts "☀"
end
